cleaned up unused variables in conftest.py and added workType to jobs_df
PyBites-Open-Source/job-seeker pull request #2
Opened 2021-10-11 10:30 UTC by Elyrie

new to open source so starting small to get my feet wet :)

2021-10-11 11:17 UTC, pedrojunqueira reviewed
@Elyrie thanks for contributing for the project. Have you ran the tests? If you added another column in the df it should break the tests. Also make sure conftest.py will still work without the request import.

2021-10-11 11:23 UTC, Elyrie commented
Oh, thanks for the input. Just tested it with running the example, I'll try to look into it more :)

2021-10-11 11:27 UTC, pedrojunqueira commented
> Oh, thanks for the input. Just tested it with running the example, I'll try to look into it more :)

Run the unittests with pytest. Then have a look at the change logs edit to reflect the changes and upgrade to version 0.0.3.

2021-10-11 11:45 UTC, Elyrie commented
> > Oh, thanks for the input. Just tested it with running the example, I'll try to look into it more :)
> 
> Run the unittests with pytest. Then have a look at the change logs edit to reflect the changes and upgrade to version 0.0.3.

Thanks, I think I got it now

2021-10-11 11:54 UTC, Elyrie commented
Wasn't sure about how to test conftest.py so I reverted the requests import deletion. I'm pretty sure the unused variable is safe to delete, but how could I test that it works? pytest runs just test_downloader.py

2021-10-11 20:20 UTC, pedrojunqueira commented on tests/conftest.py
> +import requests
I tested locally and you are right. Do not need this variable to run

2021-10-11 20:20 UTC, pedrojunqueira commented on tests/conftest.py
> +import requests
You can remove this :)

2021-10-11 20:29 UTC, pedrojunqueira requested changes
Hi @Elyrie, I think it is almost there. You can remove the `requests` import in conftest and one last change. Can you change the .csv in `/example` folder with an example including the column you added?. About [conftest.py](https://docs.pytest.org/en/6.2.x/fixture.html#scope-sharing-fixtures-across-classes-modules-packages-or-session) it does not run any tests. It is just a configuration file that pytest looks and do some setup before tests are run. If you make those final changes then it is got to go. Thanks

2021-10-11 23:27 UTC, Elyrie commented
Ok, great :) Did the last changes now

2021-10-12 09:51 UTC, pedrojunqueira commented on tests/conftest.py
> +import requests
removed.

2021-10-12 09:51 UTC, pedrojunqueira commented on tests/conftest.py
> +import requests
done

2021-10-12 09:53 UTC, merged